### ISSUE TITLE
UnsatisfiedLinkError...probe.dll: The specified procedure could not be found

### ISSUE THREAD

**Issue by bagaturchess** [VedantJoshi1409/stockfish_nnue_probe#1]
Hi,
the uploaded dll file doesn't work on my side via Java.
It says Exception in thread "main" java.lang.UnsatisfiedLinkError: ... probe.dll: The specified procedure could not be found
Could you please check whether it works on your side?
Best regards, Krasimir

**Comment by VedantJoshi1409** [comment]
Hi,

Based on your next issue I assume you have figured out the reason so I will close this issue :)

Thank you,
Vedant Joshi

**Comment by bagaturchess** [comment]
Hi Vedant Joshi,

it was not related with the package just maybe the dll was old or broken. Now you rebuilt it so it should be fine.

Best regards,
Krasimir
