### ISSUE TITLE
Cannot directly import or include a class from the default package

### ISSUE THREAD

**Issue by bagaturchess** [VedantJoshi1409/stockfish_nnue_probe#2]
Hi,

in Java, you cannot directly import or include a class from the default package (i.e., a class without a package declaration) into a class that is within a named package. This is a limitation of the Java language and is intended to encourage better organization and modularization of code.
So, it is better to add package name to the NNUEBridge class and rebuild the *.h file and the dll.

Best regards,
Krasimir

**Comment by VedantJoshi1409** [comment]
Hi,

I will rebuild with a package but wouldn't you need to rebuild with your specific path in mind? For example in your JNI, your path was bagaturchess_nnue_NNUEJNIBridge. I added the instructions to rebuild for specific situations [here](https://github.com/VedantJoshi1409/stockfish_nnue_probe?tab=readme-ov-file#java-installation-guide).

Thank you,
Vedant Joshi

**Comment by VedantJoshi1409** [comment]
I have rebuilt the shared library and it is now in a package. Hopefully it works :)

**Comment by bagaturchess** [comment]
> Hi,
> 
> I will rebuild with a package but wouldn't you need to rebuild with your specific path in mind? For example in your JNI, your path was bagaturchess_nnue_NNUEJNIBridge. I added the instructions to rebuild for specific situations [here](https://github.com/VedantJoshi1409/stockfish_nnue_probe?tab=readme-ov-file#java-installation-guide).
> 
> Thank you, Vedant Joshi

Hi Vedant Joshi,
It is not necessary for me to put the class in my package, I just want to be able to import it in my classes. With package it is possible :-)
Best regards,
Krasimir

**Comment by bagaturchess** [comment]
> I have rebuilt the shared library and it is now in a package. Hopefully it works :)

Hi Vedant Joshi,

I assume you have test it. I am not able to test it, because I already made workarounds to make it working. Now it works on my side with the workarounds and I am testing the Engine strength with it integrated.

Best regards,
Krasimir
